### ISSUE TITLE
Token Usage

### ISSUE THREAD

**Issue by zina-bug** [advaith1/stickers#8]
Advaith,

Is it necessary to use a bot token or a user token? Kindly advise. I am trying to run the site but a bot token is giving me an error. If we have to use a user token is Nitro needed?

**Comment by zina-bug** [comment]
@advaith1 Thank you for your time in advance.

**Comment by advaith1** [comment]
you don't need a token anymore but I use a bot token because the API required a token originally.

**Comment by zina-bug** [comment]
Thank you for your answer. Is it permitted to self-host this privately for one of my servers? I was going to modify the code to display all the stickers in a specific server.

**Comment by advaith1** [comment]
Sure, go ahead.

**Comment by zina-bug** [comment]
Thank you.
